postsubmits:
  GoogleCloudPlatform/osconfig:
  - name: osconfig-build
    cluster: gcp-guest
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["gcp-guest", "us-west1-a", "./packaging/build_packages_wf.json", "gs://osconfig-agent-package/"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account
    max_concurrency: 10
    branches:
    - ^master$

presubmits:
  GoogleCloudPlatform/osconfig:
  - name: osconfig-presubmit-build
    cluster: gcp-guest
    run_if_changed: ".*/packaging/.*"
    trigger: "(?m)^/packagebuild$"
    rerun_command: "/packagebuild"
    context: prow/presubmit/packagebuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["gcp-guest", "us-west1-a", "./packaging/build_packages_wf.json"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account
  - name: osconfig-presubmit-gocheck
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gocheck$"
    rerun_command: "/gocheck"
    context: prow/presubmit/gocheck
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gocheck:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: osconfig-presubmit-gobuild
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gobuild$"
    rerun_command: "/gobuild"
    context: prow/presubmit/gobuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gobuild:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: osconfig-presubmit-gotest
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gotest$"
    rerun_command: "/gotest"
    context: prow/presubmit/gotest
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gotest:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: codecov
          mountPath: /etc/codecov
          readOnly: true
      volumes:
      - name: codecov
        secret:
          secretName: codecov

  GoogleCloudPlatform/guest-agent:
  - name: guest-agent-presubmit-gocheck
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gocheck$"
    rerun_command: "/gocheck"
    context: prow/presubmit/gocheck
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gocheck:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: guest-agent-presubmit-gobuild
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gobuild$"
    rerun_command: "/gobuild"
    context: prow/presubmit/gobuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gobuild:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: guest-agent-presubmit-gotest
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gotest$"
    rerun_command: "/gotest"
    context: prow/presubmit/gotest
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gotest:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: codecov
          mountPath: /etc/codecov
          readOnly: true
      volumes:
      - name: codecov
        secret:
          secretName: codecov

  GoogleCloudPlatform/guest-logging-go:
  - name: guest-logging-presubmit-gocheck
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gocheck$"
    rerun_command: "/gocheck"
    context: prow/presubmit/gocheck
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gocheck:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: guest-logging-presubmit-gobuild
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gobuild$"
    rerun_command: "/gobuild"
    context: prow/presubmit/gobuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gobuild:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: guest-logging-presubmit-gotest
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gotest$"
    rerun_command: "/gotest"
    context: prow/presubmit/gotest
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gotest:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: codecov
          mountPath: /etc/codecov
          readOnly: true
      volumes:
      - name: codecov
        secret:
          secretName: codecov

  GoogleCloudPlatform/compute-image-packages:
  - name: packages-presubmit-selinux-module
    cluster: gcp-guest
    run_if_changed: ".*/policy/.*"
    trigger: "(?m)^/modcheck$"
    rerun_command: "/modcheck"
    context: prow/presubmit/selinux_module_check
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/selinux-tools:latest
        imagePullPolicy: Always
        command:
        - "./packages/google-compute-engine-oslogin/policy/validate.sh"

  GoogleCloudPlatform/guest-oslogin:
  - name: oslogin-presubmit-selinux-module
    cluster: gcp-guest
    run_if_changed: ".*/policy/.*"
    trigger: "(?m)^/modcheck$"
    rerun_command: "/modcheck"
    context: prow/presubmit/selinux_module_check
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/selinux-tools:latest
        imagePullPolicy: Always
        command:
        - "./selinux/validate.sh"
  - name: oslogin-presubmit-build
    cluster: gcp-guest
    run_if_changed: ".*\\.(cc?|h)$"
    trigger: "(?m)^/build$"
    rerun_command: "/build"
    context: prow/presubmit/build
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/debian:latest
        imagePullPolicy: Always
        command:
        - make
        args:
        - prowbuild
  - name: oslogin-presubmit-test
    cluster: gcp-guest
    run_if_changed: ".*\\.(cc?|h)$"
    trigger: "(?m)^/test$"
    rerun_command: "/test"
    context: prow/presubmit/test
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/debian:latest
        imagePullPolicy: Always
        command:
        - make
        args:
        - prowtest
